"""normalized image model and library

Revision ID: 45aa55291a12
Revises: 
Create Date: 2026-04-23 21:29:10.024443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45aa55291a12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'image', ['image_id'], ['id'])
        batch_op.drop_column('image_path')
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sticker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
