"""add provider and pollinations fields to settings

Revision ID: 67bda19b7e32
Revises: 
Create Date: 2026-04-22 20:23:23.647088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67bda19b7e32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('openrouter_model', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('pollinations_api_key', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('pollinations_model', sa.String(length=100), nullable=True))
        batch_op.drop_column('model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('pollinations_model')
        batch_op.drop_column('pollinations_api_key')
        batch_op.drop_column('openrouter_model')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
